version: '3'

services:
  logs:
    build:
      context: ./logs

  mqtt:
    build:
      context: ./mqtt
    restart: always
    volumes:
      - mqtt_data:/mosquitto/data/

volumes:
  mqtt_data: { }